### ISSUE TITLE
Именование классов и стилей

### ISSUE THREAD

**Issue by aleksch** [prostokolya94/jamshop#1]
https://github.com/prostokolya94/jamshop/blob/467b6916096d8789374854fbd1b59350f5d6ed90/style.css#L56

Статья про правильное именование css классов https://habr.com/ru/post/303174/. Особенно обрати внимание на пятый пункт. Очень сильно ухудшается чтение.

**Comment by prostokolya94** [comment]
исправил остатки верблюжего чемодана (как говорим мы - англичане) и разделил названия дефисами

**Comment by aleksch** [comment]
Если поправил и закомитил закрывай это issue
