### ISSUE TITLE
Использовать встроеные шрифты

### ISSUE THREAD

**Issue by aleksch** [prostokolya94/jamshop#3]
https://github.com/prostokolya94/jamshop/blob/467b6916096d8789374854fbd1b59350f5d6ed90/index.html#L9

https://html5book.ru/pravilo-font-face
Подробный гайд по шрифтам и текстам (слайды - https://urfu-2018.github.io/slides/markup/03-fonts-and-text, запись - https://www.youtube.com/watch?v=RWn0UOj3s2k&list=PLKaafC45L_SQEH2hprLYvX_IpN1cMV-5H&index=5)
скачать нужные шрифты можно здесь - https://fonts.google.com/
шрифты должны храниться у тебя скачанными файлами и подключаться с `@font-face`

**Comment by prostokolya94** [comment]
подключил шрифты чз fontface
