### ISSUE TITLE
Замечания по верстке

### ISSUE THREAD

**Issue by aleksch** [prostokolya94/jamshop#4]
#### 2. `class="product"` 
```
.product {
  width: 262px;
  height: 64px; <- лишнее (1)
  display: flex;
  align-items: center; <- лишнее
  justify-content: space-between;
  margin:29px auto 30px  auto;
 }
```
(1) Чем меньше использовать высоту тем лучше. `<div>` и другие блочные теги автоматом подстраиваются под высоту элемента.
#### `<div class="price">$10.99</div>`
```
.price {
  width: 108px; <- лишнее (1)
  height: 33px; <- лишнее
  font-family: Roboto Condensed; <- можно задать body и не надо будет дублировать
  font-size: 35px;
  line-height: 32px;
  display: flex; <- лишнее (1)
  margin: 0 auto; <- лишнее (1)
}
```
(1) По умолчанию `div` пытается занять 100% ширину. Центрировать текст можно свойством `text-align` все отмеченные свойства не понадобятся. И если будет другая сумма, например большая на разряд то все поломается 😿 
#### 3. `<div class="addproduct">`
Внутри должны быть `input` и `button`
#### 4. `<div class="buybutton">Purchase Now</div>`
Шрифт не по макету (если он везде одинаковый можно задать его `body`)
#### 5. `<div class="smalltext">`
Цвет не по дизайну и нет иконки.
#### 6. `-webkit-...`
Используется для совместимости со старыми браузерами сейчас все текущие его поддерживают без префиксов (chrome поддерживает с 36 версии, текущая 80), так что его нужно везде убрать. Для проверки можно использовать этой ссылкой https://caniuse.com/#search=transform

**Comment by prostokolya94** [comment]
Прошелся по всем замечаниям, чуть не умер, но дело сделано
